@@@ A - classifier: DummyClassifier(constant=1, random_state=None, strategy='constant')
@@@ B - threshold stop at: 1
@@@ C - Repeat number: 1
/Users/author1/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:463: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/author1/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:464: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/author1/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/author1/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:466: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/author1/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:467: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
@@@ D - common_header:  {'F104', 'F3-FileInputStream', 'F117', 'F3-Class<?>[]', 'F3-InputStream', 'F22', 'F115', 'F71-jhook@apache.org', 'F71-slaurent@apache.org', 'F15-NA', 'category', 'F3-Class[]', 'F15-private', 'F15-protected', 'F71-yoavs@apache.org', 'F71-markt@apache.org', 'F120', 'F71-fhanik@apache.org', 'F71-fcarrion@apache.org', 'F41', 'F71-kfujino@apache.org', 'F3-long', 'F3-null', 'F3-ELContext', 'F110', 'F71-remm@apache.org', 'F105', 'F3-int', 'F3-String[]', 'F3-Integer', 'F71-mturk@apache.org', 'F71-funkman@apache.org', 'F71-costin@apache.org', 'F126', 'F72', 'F3-NA', 'F71-timw@apache.org', 'F68', 'F3-Object', 'F3-Member', 'F77', 'F3-Long', 'F71-pero@apache.org', 'F25', 'F65', 'F3-byte[]', 'F123', 'F71-kkolinko@apache.org', 'F71-schultz@apache.org', 'F15-public', 'F3-ObjectName', 'F71-billbarker@apache.org', 'F101', 'F3-String', 'F71-rjung@apache.org', 'F3-Session', 'F3-boolean', 'F116', 'F71-idarwin@apache.org', 'F3-Object[]', 'F71-jfclere@apache.org'}
Traceback (most recent call last):
  File "baseline.py", line 217, in <module>
    seed=42 + i, clf=clf, interesting_path=argv )
  File "baseline.py", line 43, in main
    training_x, training_y, testset_x, testset_y, training_canonical_ids, testing_canonical_ids = cleaning.data_clean(path, [interesting_path], seed)
  File "/Users/author1/repos/SA_public/src/cleaning.py", line 340, in data_clean
    testset_y = testing_trim.iloc[:, -1]
  File "/Users/author1/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/author1/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 2013, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/author1/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 222, in _has_valid_tuple
    self._validate_key(k, i)
  File "/Users/author1/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1957, in _validate_key
    self._validate_integer(key, axis)
  File "/Users/author1/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 2009, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
